{
    'name': 'School Management',
    'author': 'Adarsh',
    'version': '17.0.1.0.0',
    'summary': 'School Management',
    'depends': ['base', 'mail', 'sale', 'contacts', 'base_automation'],
    'data': [
        'security/school_management_user_groups_security.xml',
        'security/school_leave_security.xml',
        'security/school_management_company_security.xml',
        'security/school_event_security.xml',
        'security/school_exam_security.xml',
        'security/school_class_security.xml',
        'security/school_student_security.xml',
        'security/ir.model.access.csv',
        'data/event_email_template_data.xml',
        'data/ir_actions_server_data.xml',
        'data/automatic_action_data.xml',
        'data/ir_cron_data.xml',
        'data/ir_sequence_data.xml',
        'data/res_partner_data.xml',
        'data/school_department_data.xml',
        'data/school_class_data.xml',
        'data/school_subject_data.xml',
        'views/school_student_views.xml',
        'views/school_subject_views.xml',
        'views/school_event_views.xml',
        'views/school_department_views.xml',
        'views/school_club_views.xml',
        'views/school_class_views.xml',
        'views/school_student_class_views.xml',
        'views/school_academic_views.xml',
        'views/sale_order_views.xml',
        'views/res_partner_views.xml',
        'views/school_employee_views.xml',
        'views/school_leave_views.xml',
        'views/school_exam_views.xml',
    ],
    'sequence': -100,
    'application': True,
}
