from . import school_department
from . import school_class
from . import school_subject
from . import school_academic_year
from . import school_student
from . import school_club
from . import school_event
from . import sale_order
from . import res_partner
from . import school_leave
from . import school_exam
